services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DrBlitz\GoogleIndexer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  DrBlitz\GoogleIndexer\Controller\ModuleController:
    tags: ['backend.controller']

  DrBlitz\GoogleIndexer\Service\GoogleIndexingApi:
    public: true
